//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodegaInternexa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class INTERNEXAEntities : DbContext
    {
        public INTERNEXAEntities()
            : base("name=INTERNEXAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<obtenerBodegaSolps_Result> obtenerBodegaSolps(string idservicio, string cliente, string nombreservicio, string os)
        {
            var idservicioParameter = idservicio != null ?
                new ObjectParameter("idservicio", idservicio) :
                new ObjectParameter("idservicio", typeof(string));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            var nombreservicioParameter = nombreservicio != null ?
                new ObjectParameter("nombreservicio", nombreservicio) :
                new ObjectParameter("nombreservicio", typeof(string));
    
            var osParameter = os != null ?
                new ObjectParameter("os", os) :
                new ObjectParameter("os", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtenerBodegaSolps_Result>("obtenerBodegaSolps", idservicioParameter, clienteParameter, nombreservicioParameter, osParameter);
        }
    
        public virtual ObjectResult<ValidacionBodegaSolps_Result> ValidacionBodegaSolps(string idservicio)
        {
            var idservicioParameter = idservicio != null ?
                new ObjectParameter("idservicio", idservicio) :
                new ObjectParameter("idservicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidacionBodegaSolps_Result>("ValidacionBodegaSolps", idservicioParameter);
        }
    }
}
